### ISSUE TITLE
Bind with Union returns no results

### ISSUE THREAD

**Issue by misinco** [eclipse/rdf4j-storage#98] opened 2018-08-16 19:36 UTC
I have a query that returns results on GraphDB but not when using the sail memory store, which is used for unit tests.  I am using version 2.3.2.

The issue appears to be when doing:
`{bind (?b1 as ?id)}
UNION {bind (?b2 as ?id)}`

I've attached a zip with 2 files.  One shows a screen shot of the results of the query from GraphDB with the same test data and the other is a Java file that shows the issue.
[sail_repo_test.zip](https://github.com/eclipse/rdf4j-storage/files/2295000/sail_repo_test.zip)

**Comment by barthanssens** [comment] 2018-08-23 11:40
Just to check if it could be a regression: which version of GraphDB are you using ? 8.6 ?

**Comment by misinco** [comment] 2018-08-23 20:11
@barthanssens 8.5

**Comment by jeenbroekstra** [comment] 2018-09-04 00:38
The query being done is:

```
PREFIX dc: <http://purl.org/dc/elements/1.1/>
select ?id ?prop ?value where { 
	?b1 dc:title "A new book" .
    ?b2 dc:title "A second book" .
    {bind (?b1 as ?id)}
    UNION {bind (?b2 as ?id)}
    ?id ?prop ?value
}
```
Confirmed a bug in the QueryJoinOptimizer, which incorrectly tries to evaluate the bind late, leaving `?id` empty at the time its BGP is evaluated.

**Comment by jeenbroekstra** [comment] 2018-09-04 01:53
I had a closer look and I believe that in this case, RDF4J is actually correct to return an empty set.

The problem is that the `BIND` operations are part of a  `UNION` pattern. `BIND` is [defined to operate](https://www.w3.org/TR/sparql11-query/#bind) on 'the preceding basic graph pattern'. In this case, that preceding BGP is the  (empty) `UNION` argument, _not_ the triple patterns outside the `UNION`. SPARQL evaluation happens bottom-up. In other words, the values assigned to `?b1` and `?b2` are not available at the time the `BIND` gets evaluated, leading to `?id` being unbound. 

To get the desired behaviour, you'd need to rewrite the query:

```
PREFIX dc: <http://purl.org/dc/elements/1.1/>
select ?id ?prop ?value where { 
        {?b1 dc:title "A new book" . bind (?b1 as ?id)}
        UNION 
        {?b2 dc:title "A second book" . bind (?b2 as ?id)}
      ?id ?prop ?value
}
```

Or, much simpler even, without using `BIND` at all:

```
PREFIX dc: <http://purl.org/dc/elements/1.1/>
select ?id ?prop ?value where { 
        {?id dc:title "A new book" }
        UNION 
        {?id dc:title "A second book" }
      ?id ?prop ?value
}
```

I'm not sure why you get a different result in GraphDB, I can only assume that its query planner does something funky with determining which variables are in-scope. But as far as I can tell its behavior is not conform the specification.

**Closed** 2018-09-04 02:11 UTC
Labels: bug, wontfix
